### ISSUE TITLE
Not compatible with python 2.7

### ISSUE THREAD

**Issue by eranco74** [sharbov/open-cli#1]

**Comment by eranco74** [comment]
Traceback (most recent call last):
  File "/usr/bin/open-cli", line 6, in <module>
    from open_cli.main import main
  File "/usr/lib/python3.5/site-packages/open_cli/main.py", line 4, in <module>
    from open_cli import cli
  File "/usr/lib/python3.5/site-packages/open_cli/cli.py", line 54
    f"{self.name} $ ",
                    ^
SyntaxError: invalid syntax

**Comment by sharbov** [comment]
fixed
